In [4]:
import tensorflow as tf

In [5]:
scalar = tf.constant(20)
print(scalar)

tf.Tensor(20, shape=(), dtype=int32)


In [6]:
vector = tf.constant([10, 20, 30, 40])
print(vector)

tf.Tensor([10 20 30 40], shape=(4,), dtype=int32)


In [7]:
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])
print(matrix)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [11]:
matrix1 = tf.constant([[1, 1, 1], [1, 1, 1]])
print(matrix1)

tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


In [10]:
matrix0 = tf.constant([[0, 0, 0], [0, 0, 0]])
print(matrix0)

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)
