In [4]:
import tensorflow as tf

In [5]:
scalar = tf.constant(20)
print(scalar)

tf.Tensor(20, shape=(), dtype=int32)


In [6]:
vector = tf.constant([10, 20, 30, 40])
print(vector)

tf.Tensor([10 20 30 40], shape=(4,), dtype=int32)


In [31]:
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])
print(matrix)

print(tf.cast(matrix, tf.float32))

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


In [29]:
ones = tf.ones((2, 3))
print(ones)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [12]:
zeros = tf.zeros((2, 3))
print(zeros)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [27]:
range = tf.range(1, 11)
print(range)

range = tf.cast(range, tf.float32)
print(range)

print(tf.rank(range))
print(range.dtype)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10], shape=(10,), dtype=int32)
tf.Tensor([ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.], shape=(10,), dtype=float32)
tf.Tensor(1, shape=(), dtype=int32)
<dtype: 'float32'>


In [59]:
matrix = tf.constant([[30, 40, 50], [60, 70, 80], [90, 100, 110]])

matrix = tf.transpose(matrix)
print(matrix)

tf.Tensor(
[[ 30  60  90]
 [ 40  70 100]
 [ 50  80 110]], shape=(3, 3), dtype=int32)


In [ ]:
a = tf.constant([[10, 20, 30]])
b = tf.constant([[1], [2], [3]])

sum = tf.add(a, b)
print(sum)

diff = tf.subtract(a, b)
print(diff)

multi = tf.multiply(a, b)
print(multi)

div = tf.divide(a, b)
print(div)

square = tf.square(a)
print(square)

root = tf.sqrt(tf.cast(a, tf.float32))
print(root)




tf.Tensor(
[[11 21 31]
 [12 22 32]
 [13 23 33]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 9 19 29]
 [ 8 18 28]
 [ 7 17 27]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[10 20 30]
 [20 40 60]
 [30 60 90]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[10.         20.         30.        ]
 [ 5.         10.         15.        ]
 [ 3.33333333  6.66666667 10.        ]], shape=(3, 3), dtype=float64)
tf.Tensor([[100 400 900]], shape=(1, 3), dtype=int32)
tf.Tensor([[3.1622777 4.472136  5.477226 ]], shape=(1, 3), dtype=float32)
tf.Tensor(60, shape=(), dtype=int32)
tf.Tensor(20, shape=(), dtype=int32)
tf.Tensor(30, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)


In [89]:
overallsum = tf.reduce_sum(a)
print(overallsum)   

mean = tf.reduce_mean(a)
print(mean)

mode = tf.reduce_max(a)
print(mode)

min = tf.reduce_min(a)
print(min)

max = tf.argmax(a)
print(max)

tf.Tensor(60, shape=(), dtype=int32)
tf.Tensor(20, shape=(), dtype=int32)
tf.Tensor(30, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor([0 0 0], shape=(3,), dtype=int64)


NameError: name 'x' is not defined